name = "html-trackers"
main = "worker.js"
compatibility_date = "2024-12-01"

# KV Namespace — create with: wrangler kv namespace create TRACKER_STATE
# Then paste the id below
[[kv_namespaces]]
binding = "TRACKER_STATE"
id = "988b27e5e34242039ca862df143e4a39"
